screen -dm matlab -nodisplay -r "gplF1;exit"
screen -dm matlab -nodisplay -r "gplF2;exit"
screen -dm matlab -nodisplay -r "gplF3;exit"
screen -dm matlab -nodisplay -r "gplF4;exit"
screen -dm matlab -nodisplay -r "gplF5;exit"
screen -dm matlab -nodisplay -r "gplF6;exit"
screen -dm matlab -nodisplay -r "gplF7;exit"
screen -dm matlab -nodisplay -r "gplF8;exit"

screen -dm matlab -nodisplay -r "gplT1;exit"
screen -dm matlab -nodisplay -r "gplT2;exit"
screen -dm matlab -nodisplay -r "gplT3;exit"
screen -dm matlab -nodisplay -r "gplT4;exit"
screen -dm matlab -nodisplay -r "gplT5;exit"
screen -dm matlab -nodisplay -r "gplT6;exit"
screen -dm matlab -nodisplay -r "gplT7;exit"
screen -dm matlab -nodisplay -r "gplT8;exit"

screen -dm matlab -nodisplay -r "gplt4lm1;exit"
screen -dm matlab -nodisplay -r "gplt4lm2;exit"
screen -dm matlab -nodisplay -r "gplt4lm3;exit"
screen -dm matlab -nodisplay -r "gplFt4lm4;exit"
screen -dm matlab -nodisplay -r "gplFt4lm5;exit"
screen -dm matlab -nodisplay -r "gplFt4lm6;exit"
screen -dm matlab -nodisplay -r "gplFt4lm7;exit"
screen -dm matlab -nodisplay -r "gplFt4lm8;exit"

