screen -dm matlab -nodisplay -r "gplF1;exit"
screen -dm matlab -nodisplay -r "gplF2;exit"
screen -dm matlab -nodisplay -r "gplF3;exit"
screen -dm matlab -nodisplay -r "gplF4;exit"
screen -dm matlab -nodisplay -r "gplF5;exit"
screen -dm matlab -nodisplay -r "gplF6;exit"