screen -dm matlab -nodisplay -r "servT0;exit"
screen -dm matlab -nodisplay -r "servT00;exit"
screen -dm matlab -nodisplay -r "gplF3;exit"
screen -dm matlab -nodisplay -r "gplF4;exit"
screen -dm matlab -nodisplay -r "gplF5;exit"
screen -dm matlab -nodisplay -r "gplF6;exit"