screen -dm matlab -nodisplay -r "gplmean2;exit"
screen -dm matlab -nodisplay -r "gplmean4;exit"
screen -dm matlab -nodisplay -r "gplmean6;exit"
screen -dm matlab -nodisplay -r "gplmean8;exit"
screen -dm matlab -nodisplay -r "gplmean9;exit"