
screen -dm matlab -nodisplay -r "gplT1;exit"
screen -dm matlab -nodisplay -r "gplT2;exit"
screen -dm matlab -nodisplay -r "gplT3;exit"
screen -dm matlab -nodisplay -r "gplT4;exit"
screen -dm matlab -nodisplay -r "gplT5;exit"
screen -dm matlab -nodisplay -r "gplT6;exit"
screen -dm matlab -nodisplay -r "gplT7;exit"
screen -dm matlab -nodisplay -r "gplT8;exit"
screen -dm matlab -nodisplay -r "gplT9;exit"
screen -dm matlab -nodisplay -r "gplT10;exit"
screen -dm matlab -nodisplay -r "gplT11;exit"
screen -dm matlab -nodisplay -r "gplT12;exit"
screen -dm matlab -nodisplay -r "gplT13;exit"
screen -dm matlab -nodisplay -r "gplT14;exit"
screen -dm matlab -nodisplay -r "gplT15;exit"
screen -dm matlab -nodisplay -r "gplT16;exit"
